packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - better-sqlite3
  - esbuild
  - lefthook
  - sharp
  - workerd

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - lefthook
  - workerd
