name: Setup pnpm
description: pnpmと依存関係をインストール

runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Setup mise
      uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
      with:
        install: true
        cache: true

    - name: Install safe-chain
      shell: bash
      run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci

    - name: Install dependencies
      shell: bash
      run: pnpm install
