name: Setup pnpm
description: pnpmと依存関係をインストール

runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        install: true
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm install
