/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ClosedBetaRouteImport } from './routes/closed-beta'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportLayoutRouteImport } from './routes/report/_layout'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as UserLayoutUserIdRouteImport } from './routes/user/_layout.$userId'
import { Route as ReportLayoutUserRouteImport } from './routes/report/_layout/user'
import { Route as ReportLayoutImageRouteImport } from './routes/report/_layout/image'
import { Route as ApiR2SplatRouteImport } from './routes/api/r2/$'
import { Route as ApiAuthRedirectRouteImport } from './routes/api/auth/redirect'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UserLayoutUserIdIndexRouteImport } from './routes/user/_layout.$userId/index'
import { Route as UserLayoutUserIdTagIndexRouteImport } from './routes/user/_layout.$userId/tag/index'
import { Route as UserLayoutUserIdTagTagIdRouteImport } from './routes/user/_layout.$userId/tag/$tagId'
import { Route as UserLayoutUserIdImageImageIdRouteImport } from './routes/user/_layout.$userId/image.$imageId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosedBetaRoute = ClosedBetaRouteImport.update({
  id: '/closed-beta',
  path: '/closed-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportLayoutRoute = ReportLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ReportRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutUserIdRoute = UserLayoutUserIdRouteImport.update({
  id: '/user/_layout/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportLayoutUserRoute = ReportLayoutUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ReportLayoutRoute,
} as any)
const ReportLayoutImageRoute = ReportLayoutImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ReportLayoutRoute,
} as any)
const ApiR2SplatRoute = ApiR2SplatRouteImport.update({
  id: '/api/r2/$',
  path: '/api/r2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRedirectRoute = ApiAuthRedirectRouteImport.update({
  id: '/api/auth/redirect',
  path: '/api/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutUserIdIndexRoute = UserLayoutUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLayoutUserIdRoute,
} as any)
const UserLayoutUserIdTagIndexRoute =
  UserLayoutUserIdTagIndexRouteImport.update({
    id: '/tag/',
    path: '/tag/',
    getParentRoute: () => UserLayoutUserIdRoute,
  } as any)
const UserLayoutUserIdTagTagIdRoute =
  UserLayoutUserIdTagTagIdRouteImport.update({
    id: '/tag/$tagId',
    path: '/tag/$tagId',
    getParentRoute: () => UserLayoutUserIdRoute,
  } as any)
const UserLayoutUserIdImageImageIdRoute =
  UserLayoutUserIdImageImageIdRouteImport.update({
    id: '/image/$imageId',
    path: '/image/$imageId',
    getParentRoute: () => UserLayoutUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/closed-beta': typeof ClosedBetaRoute
  '/settings': typeof SettingsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/signup': typeof AuthSignupRoute
  '/report': typeof ReportLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/redirect': typeof ApiAuthRedirectRoute
  '/api/r2/$': typeof ApiR2SplatRoute
  '/report/image': typeof ReportLayoutImageRoute
  '/report/user': typeof ReportLayoutUserRoute
  '/user/$userId': typeof UserLayoutUserIdRouteWithChildren
  '/user/$userId/': typeof UserLayoutUserIdIndexRoute
  '/user/$userId/image/$imageId': typeof UserLayoutUserIdImageImageIdRoute
  '/user/$userId/tag/$tagId': typeof UserLayoutUserIdTagTagIdRoute
  '/user/$userId/tag': typeof UserLayoutUserIdTagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/closed-beta': typeof ClosedBetaRoute
  '/settings': typeof SettingsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/signup': typeof AuthSignupRoute
  '/report': typeof ReportLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/redirect': typeof ApiAuthRedirectRoute
  '/api/r2/$': typeof ApiR2SplatRoute
  '/report/image': typeof ReportLayoutImageRoute
  '/report/user': typeof ReportLayoutUserRoute
  '/user/$userId': typeof UserLayoutUserIdIndexRoute
  '/user/$userId/image/$imageId': typeof UserLayoutUserIdImageImageIdRoute
  '/user/$userId/tag/$tagId': typeof UserLayoutUserIdTagTagIdRoute
  '/user/$userId/tag': typeof UserLayoutUserIdTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/closed-beta': typeof ClosedBetaRoute
  '/settings': typeof SettingsRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/signup': typeof AuthSignupRoute
  '/report/_layout': typeof ReportLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/redirect': typeof ApiAuthRedirectRoute
  '/api/r2/$': typeof ApiR2SplatRoute
  '/report/_layout/image': typeof ReportLayoutImageRoute
  '/report/_layout/user': typeof ReportLayoutUserRoute
  '/user/_layout/$userId': typeof UserLayoutUserIdRouteWithChildren
  '/user/_layout/$userId/': typeof UserLayoutUserIdIndexRoute
  '/user/_layout/$userId/image/$imageId': typeof UserLayoutUserIdImageImageIdRoute
  '/user/_layout/$userId/tag/$tagId': typeof UserLayoutUserIdTagTagIdRoute
  '/user/_layout/$userId/tag/': typeof UserLayoutUserIdTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/closed-beta'
    | '/settings'
    | '/auth/error'
    | '/auth/signup'
    | '/report'
    | '/api/auth/$'
    | '/api/auth/redirect'
    | '/api/r2/$'
    | '/report/image'
    | '/report/user'
    | '/user/$userId'
    | '/user/$userId/'
    | '/user/$userId/image/$imageId'
    | '/user/$userId/tag/$tagId'
    | '/user/$userId/tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/closed-beta'
    | '/settings'
    | '/auth/error'
    | '/auth/signup'
    | '/report'
    | '/api/auth/$'
    | '/api/auth/redirect'
    | '/api/r2/$'
    | '/report/image'
    | '/report/user'
    | '/user/$userId'
    | '/user/$userId/image/$imageId'
    | '/user/$userId/tag/$tagId'
    | '/user/$userId/tag'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/closed-beta'
    | '/settings'
    | '/auth/error'
    | '/auth/signup'
    | '/report/_layout'
    | '/api/auth/$'
    | '/api/auth/redirect'
    | '/api/r2/$'
    | '/report/_layout/image'
    | '/report/_layout/user'
    | '/user/_layout/$userId'
    | '/user/_layout/$userId/'
    | '/user/_layout/$userId/image/$imageId'
    | '/user/_layout/$userId/tag/$tagId'
    | '/user/_layout/$userId/tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ClosedBetaRoute: typeof ClosedBetaRoute
  SettingsRoute: typeof SettingsRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthRedirectRoute: typeof ApiAuthRedirectRoute
  ApiR2SplatRoute: typeof ApiR2SplatRoute
  UserLayoutUserIdRoute: typeof UserLayoutUserIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closed-beta': {
      id: '/closed-beta'
      path: '/closed-beta'
      fullPath: '/closed-beta'
      preLoaderRoute: typeof ClosedBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/_layout': {
      id: '/report/_layout'
      path: ''
      fullPath: '/report'
      preLoaderRoute: typeof ReportLayoutRouteImport
      parentRoute: typeof ReportRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_layout/$userId': {
      id: '/user/_layout/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserLayoutUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/_layout/user': {
      id: '/report/_layout/user'
      path: '/user'
      fullPath: '/report/user'
      preLoaderRoute: typeof ReportLayoutUserRouteImport
      parentRoute: typeof ReportLayoutRoute
    }
    '/report/_layout/image': {
      id: '/report/_layout/image'
      path: '/image'
      fullPath: '/report/image'
      preLoaderRoute: typeof ReportLayoutImageRouteImport
      parentRoute: typeof ReportLayoutRoute
    }
    '/api/r2/$': {
      id: '/api/r2/$'
      path: '/api/r2/$'
      fullPath: '/api/r2/$'
      preLoaderRoute: typeof ApiR2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/redirect': {
      id: '/api/auth/redirect'
      path: '/api/auth/redirect'
      fullPath: '/api/auth/redirect'
      preLoaderRoute: typeof ApiAuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_layout/$userId/': {
      id: '/user/_layout/$userId/'
      path: '/'
      fullPath: '/user/$userId/'
      preLoaderRoute: typeof UserLayoutUserIdIndexRouteImport
      parentRoute: typeof UserLayoutUserIdRoute
    }
    '/user/_layout/$userId/tag/': {
      id: '/user/_layout/$userId/tag/'
      path: '/tag'
      fullPath: '/user/$userId/tag'
      preLoaderRoute: typeof UserLayoutUserIdTagIndexRouteImport
      parentRoute: typeof UserLayoutUserIdRoute
    }
    '/user/_layout/$userId/tag/$tagId': {
      id: '/user/_layout/$userId/tag/$tagId'
      path: '/tag/$tagId'
      fullPath: '/user/$userId/tag/$tagId'
      preLoaderRoute: typeof UserLayoutUserIdTagTagIdRouteImport
      parentRoute: typeof UserLayoutUserIdRoute
    }
    '/user/_layout/$userId/image/$imageId': {
      id: '/user/_layout/$userId/image/$imageId'
      path: '/image/$imageId'
      fullPath: '/user/$userId/image/$imageId'
      preLoaderRoute: typeof UserLayoutUserIdImageImageIdRouteImport
      parentRoute: typeof UserLayoutUserIdRoute
    }
  }
}

interface UserLayoutUserIdRouteChildren {
  UserLayoutUserIdIndexRoute: typeof UserLayoutUserIdIndexRoute
  UserLayoutUserIdImageImageIdRoute: typeof UserLayoutUserIdImageImageIdRoute
  UserLayoutUserIdTagTagIdRoute: typeof UserLayoutUserIdTagTagIdRoute
  UserLayoutUserIdTagIndexRoute: typeof UserLayoutUserIdTagIndexRoute
}

const UserLayoutUserIdRouteChildren: UserLayoutUserIdRouteChildren = {
  UserLayoutUserIdIndexRoute: UserLayoutUserIdIndexRoute,
  UserLayoutUserIdImageImageIdRoute: UserLayoutUserIdImageImageIdRoute,
  UserLayoutUserIdTagTagIdRoute: UserLayoutUserIdTagTagIdRoute,
  UserLayoutUserIdTagIndexRoute: UserLayoutUserIdTagIndexRoute,
}

const UserLayoutUserIdRouteWithChildren =
  UserLayoutUserIdRoute._addFileChildren(UserLayoutUserIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ClosedBetaRoute: ClosedBetaRoute,
  SettingsRoute: SettingsRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthRedirectRoute: ApiAuthRedirectRoute,
  ApiR2SplatRoute: ApiR2SplatRoute,
  UserLayoutUserIdRoute: UserLayoutUserIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
