/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClosedBetaIndexRouteImport } from './routes/closed-beta/index'
import { Route as UserLayoutUserIdRouteImport } from './routes/user/_layout.$userId'
import { Route as ApiR2SplatRouteImport } from './routes/api/r2/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UserLayoutUserIdIndexRouteImport } from './routes/user/_layout.$userId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosedBetaIndexRoute = ClosedBetaIndexRouteImport.update({
  id: '/closed-beta/',
  path: '/closed-beta/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutUserIdRoute = UserLayoutUserIdRouteImport.update({
  id: '/user/_layout/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2SplatRoute = ApiR2SplatRouteImport.update({
  id: '/api/r2/$',
  path: '/api/r2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutUserIdIndexRoute = UserLayoutUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserLayoutUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closed-beta': typeof ClosedBetaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2/$': typeof ApiR2SplatRoute
  '/user/$userId': typeof UserLayoutUserIdRouteWithChildren
  '/user/$userId/': typeof UserLayoutUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closed-beta': typeof ClosedBetaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2/$': typeof ApiR2SplatRoute
  '/user/$userId': typeof UserLayoutUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closed-beta/': typeof ClosedBetaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2/$': typeof ApiR2SplatRoute
  '/user/_layout/$userId': typeof UserLayoutUserIdRouteWithChildren
  '/user/_layout/$userId/': typeof UserLayoutUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/closed-beta'
    | '/api/auth/$'
    | '/api/r2/$'
    | '/user/$userId'
    | '/user/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/closed-beta' | '/api/auth/$' | '/api/r2/$' | '/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/closed-beta/'
    | '/api/auth/$'
    | '/api/r2/$'
    | '/user/_layout/$userId'
    | '/user/_layout/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosedBetaIndexRoute: typeof ClosedBetaIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiR2SplatRoute: typeof ApiR2SplatRoute
  UserLayoutUserIdRoute: typeof UserLayoutUserIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closed-beta/': {
      id: '/closed-beta/'
      path: '/closed-beta'
      fullPath: '/closed-beta'
      preLoaderRoute: typeof ClosedBetaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_layout/$userId': {
      id: '/user/_layout/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserLayoutUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2/$': {
      id: '/api/r2/$'
      path: '/api/r2/$'
      fullPath: '/api/r2/$'
      preLoaderRoute: typeof ApiR2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_layout/$userId/': {
      id: '/user/_layout/$userId/'
      path: '/'
      fullPath: '/user/$userId/'
      preLoaderRoute: typeof UserLayoutUserIdIndexRouteImport
      parentRoute: typeof UserLayoutUserIdRoute
    }
  }
}

interface UserLayoutUserIdRouteChildren {
  UserLayoutUserIdIndexRoute: typeof UserLayoutUserIdIndexRoute
}

const UserLayoutUserIdRouteChildren: UserLayoutUserIdRouteChildren = {
  UserLayoutUserIdIndexRoute: UserLayoutUserIdIndexRoute,
}

const UserLayoutUserIdRouteWithChildren =
  UserLayoutUserIdRoute._addFileChildren(UserLayoutUserIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosedBetaIndexRoute: ClosedBetaIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiR2SplatRoute: ApiR2SplatRoute,
  UserLayoutUserIdRoute: UserLayoutUserIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
