permissions:
  contents: read
name: 画像最適化Workerをデプロイ

on:
  push:
    branches:
      - develop
      - main
    paths:
      - "apps/image-optimizer/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/deploy-image-optimizer.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Change directory
        run: cd apps/image-optimizer

      - name: Deploy to development environment
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: apps/image-optimizer

      - name: Deploy to production environment
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
          workingDirectory: apps/image-optimizer
